[package]
name = "mudz"
version.workspace = true
authors.workspace = true
description = "DNS cache library with an embeddable caching resolver"
documentation.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[lib]
name = "mudz"
path = "lib.rs"

[dependencies]
data-encoding.workspace = true
futures-util.workspace = true
http-body-util.workspace = true
hyper.workspace = true
hyper-rustls.workspace = true
hyper-util.workspace = true
libc.workspace = true
log.workspace = true
rand.workspace = true
serde.workspace = true
tokio.workspace = true
toml.workspace = true
tower-service.workspace = true

[dev-dependencies]
env_logger.workspace = true
